### ISSUE TITLE
repose files db vs. pkgfile

### ISSUE THREAD

**Issue by mkoskar** [falconindy/pkgfile#24]
I've used `repose -f` to generate files db for my custom repository. While `pacman -Fyy` runs ok, `pkgfile -u` reported following error:

```
error: failed to write entry header: custom/(null): Invalid or incomplete multibyte or wide character
```

I've figured that removing package `shaman-git-2.0.0_α_19_gd28fd8e-1-x86_64.pkg.tar.xz` from repository fixed the problem above (notice the `α` in the name).

Interestingly there is no problem if I don't use `repose` but regular `repo-add`, but that might be explained by the fact that `repose` produces db in a different format.

**Comment by falconindy** [comment]
Seems like something to be fixed in repose, no?

**Comment by mkoskar** [comment]
Well I admit I don't know a whole lot about pacman's db format/s. But assuming that `pacman -Fyy` works OK for both formats I thought it might be issue with `pkgfile`. At least that's where I got so far without investigation source code as such.

**Comment by falconindy** [comment]
`pacman -Fyy` and `pkgfile -uu` are not equivalent operations. pkgfile rewrites the data in order to make searching cheaper. The key difference seems to be in what program created the archive. Since repo-add works and repose doesn't, I suspect repose lacks some locale or unicode specific handling which repo-add does not.

Alternatively, can you reproduce the problem with `LC_ALL=C repo-add ...` ? That would add further evidence to repose not handling unicode properly.

**Comment by mkoskar** [comment]
Doing `LC_ALL=C repo-add` would produce bunch of warnings/errors from underlying `bsdtar` regarding that offending name/path. By inspecting files db archive it's evident that something is wrong there. Then `pkgfile -uu` will indeed produce above reported error message.

For `repose` `LC_ALL` value doesn't make difference. Inspecting resulting db, paths seem to be always UTF-8 encoded. The offending character is http://www.fileformat.info/info/unicode/char/3b1/index.htm which is indeed encoded as 0xCEB1 (see excerpt below).

```
$ xxd custom.files | head
00000000: 5061 7848 6561 6465 722f 7368 616d 616e  PaxHeader/shaman
00000010: 2d67 6974 2d32 2e30 2e30 5fce b15f 3139  -git-2.0.0_.._19
00000020: 5f67 6432 3866 6438 652d 3100 0000 0000  _gd28fd8e-1.....
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 3030 3037 3535 2000 3030 3030  ....000755 .0000
00000070: 3030 2000 3030 3030 3030 2000 3030 3030  00 .000000 .0000
00000080: 3030 3030 3135 3020 3132 3730 3530 3131  0000150 12705011
00000090: 3434 3020 3032 3132 3330 0020 7800 0000  440 021230. x...
```

**Comment by falconindy** [comment]
Right, that's inline with what I suspect. Changing LC_ALL (or any other locale vars) won't affect repose because it doesn't set any locale. Are you up for patching repose? What happens if you add `setlocale(LC_ALL, "");` early in main()? You'll need to include locale.h in order to make the compiler happy. After that, please regenerate the archive (without changing any locale vars) and report your results.

**Comment by mkoskar** [comment]
Yes, it works! Hmm, I don't know why but I didn't realize that `repose` produces same format as `repo-add` that is `tar` archive optionally compressed. I somehow got an impression it's a different format, but obviously it's the same, `*facepalm*`. Trying to untar `repose`'s resulting archive gives `tar: Ignoring unknown extended header keyword 'hdrcharset'` warnings. Should have realized that earlier, sorry for that :|.

I'll raise this with `repose` and link to this issue. Thanks ;)

**Comment by vodik** [comment]
Fixed in repose, thanks.
